### PR TITLE
fix segfaults and memleaks

### PR DESCRIPTION
**Pull request by medic123de**
fixes crashes with php-debug gtkforphp/cairo#2  and memory leak and crash for normal php gtkforphp/cairo#14

### CODE REVIEW

**Comment by auroraeosrose** [comment]
This looks good, except for the error condition - we should still bail out of everything if possible and hard destroy if we have something to destroy

**Comment by medic123de** [comment]
I completely agree, 
but given the fact, that cairo/FT does some really strange caching, i am uncertain how to cleanly destroy all data structures and leave the PHP interpreter in a sane state.

I tried FT_Done_Face, but that was obvioulsy too aggressive, because when I forced a fail, I got a segmentation fault in libc main_arena().
Furthermore, I consider it a difficult decision if we want to let the request fail, or if we let the PHP interpreter grow. 

I'd like to issue a warning in any case, but I am no PHP Coder, nor have i ever done anything with PECL. So I just don't know how it to do "the right way".
( Thats also why my code looks clumsy, and to be precise, zval *face should be filles with real_face to have a proper destroy ( i guess this is leaking right now )  but i didn't know how to do that )  


So, please see my work as a suggestion, and modify it in any way you like.

**Comment by swen100** [comment]
Sorry @medic123de but it still not working for me. I get the identical segfault.
Before i started testing, i have updated my system:
PHP 5.5.21
freetype 2.5.5
cairo 1.12.16
OpenSuse 13.1

Which versions do you have?

my backtrace:
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff582b755 in ft_mem_free () from /usr/lib64/libfreetype.so.6
(gdb) bt
#0  0x00007ffff582b755 in ft_mem_free () from /usr/lib64/libfreetype.so.6
#1  0x00007ffff582c46c in FT_Stream_ReleaseFrame () from /usr/lib64/libfreetype.so.6
#2  0x00007ffff5864177 in ?? () from /usr/lib64/libfreetype.so.6
#3  0x00007ffff5838129 in ?? () from /usr/lib64/libfreetype.so.6
#4  0x00007ffff582e69c in ?? () from /usr/lib64/libfreetype.so.6
#5  0x00007ffff582e7a1 in FT_Done_Face () from /usr/lib64/libfreetype.so.6
#6  0x00007ffff5830119 in FT_Done_Library () from /usr/lib64/libfreetype.so.6
#7  0x00007ffff5826eae in FT_Done_FreeType () from /usr/lib64/libfreetype.so.6
#8  0x00007ffff18efe3b in cairo_ft_font_face_object_destroy (object=0x7ffff7e01608) at /usr/src/cairo/cairo_ft_font.c:309
#9  0x00000000009c0b24 in zend_objects_store_del_ref_by_handle_ex (handle=3, handlers=0x143c2e0 <std_object_handlers>) at /usr/src/php-5.5.21/Zend/zend_objects_API.c:226
#10 0x00000000009c086c in zend_objects_store_del_ref (zobject=0x7ffff7fbce58) at /usr/src/php-5.5.21/Zend/zend_objects_API.c:178
#11 0x0000000000985b69 in _zval_dtor_func (zvalue=0x7ffff7fbce58, __zend_filename=0xefa2d8 "/usr/src/php-5.5.21/Zend/zend_execute.h", __zend_lineno=81)
    at /usr/src/php-5.5.21/Zend/zend_variables.c:54
#12 0x0000000000972375 in _zval_dtor (zvalue=0x7ffff7fbce58, __zend_filename=0xefa2d8 "/usr/src/php-5.5.21/Zend/zend_execute.h", __zend_lineno=81)
    at /usr/src/php-5.5.21/Zend/zend_variables.h:35
#13 0x000000000097243c in i_zval_ptr_dtor (zval_ptr=0x7ffff7fbce58, __zend_filename=0xefc290 "/usr/src/php-5.5.21/Zend/zend_variables.c", __zend_lineno=183)
    at /usr/src/php-5.5.21/Zend/zend_execute.h:81
#14 0x0000000000973672 in _zval_ptr_dtor (zval_ptr=0x7ffff7e01940, __zend_filename=0xefc290 "/usr/src/php-5.5.21/Zend/zend_variables.c", __zend_lineno=183)
    at /usr/src/php-5.5.21/Zend/zend_execute_API.c:423
#15 0x0000000000985f6c in _zval_ptr_dtor_wrapper (zval_ptr=0x7ffff7e01940) at /usr/src/php-5.5.21/Zend/zend_variables.c:183
#16 0x000000000099b11e in zend_hash_del_key_or_index (ht=0x1460668 <executor_globals+360>, arKey=0x7ffff7f02120 "fontFaceObject", nKeyLength=15, h=9924879587585365474, flag=2)
    at /usr/src/php-5.5.21/Zend/zend_hash.c:532
#17 0x0000000000977527 in zend_delete_variable (ex=0x0, ht=0x1460668 <executor_globals+360>, name=0x7ffff7f02120 "fontFaceObject", name_len=15, hash_value=9924879587585365474)
    at /usr/src/php-5.5.21/Zend/zend_execute_API.c:1612
#18 0x0000000000a2f543 in ZEND_UNSET_VAR_SPEC_CV_UNUSED_HANDLER (execute_data=0x7ffff7f82888) at /usr/src/php-5.5.21/Zend/zend_vm_execute.h:38549
#19 0x00000000009c7b82 in execute_ex (execute_data=0x7ffff7f82888) at /usr/src/php-5.5.21/Zend/zend_vm_execute.h:363
#20 0x00007ffff1d33d70 in xdebug_execute_ex (execute_data=0x7ffff7f82888) at /tmp/pear/temp/xdebug/xdebug.c:1437
#21 0x00000000009c7c0b in zend_execute (op_array=0x7ffff7fbc9c8) at /usr/src/php-5.5.21/Zend/zend_vm_execute.h:388
#22 0x000000000098958d in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /usr/src/php-5.5.21/Zend/zend.c:1327
#23 0x00000000008f7319 in php_execute_script (primary_file=0x7fffffffdf60) at /usr/src/php-5.5.21/main/main.c:2506
#24 0x0000000000a373a0 in do_cli (argc=2, argv=0x1462210) at /usr/src/php-5.5.21/sapi/cli/php_cli.c:994
#25 0x0000000000a384c2 in main (argc=2, argv=0x1462210) at /usr/src/php-5.5.21/sapi/cli/php_cli.c:1378

I think i test your code on another server.

**Comment by medic123de** [comment]
libcairo2:i386                                           1.13.0~20140204-0ubuntu1
libfreetype6:amd64                                       2.5.2-2ubuntu1
php5                                                     5.5.12+dfsg-2ubuntu4.1    ( but also works with 5.4 )

opcache enabled/disabled does not make difference here.
we use centos 6.6 at work ( where we had to update cairo + freetype ),
I use some strange ubuntu.

As said, we had the ft_memfree problem too, but worked around ( thats some kind of double-free bug)
I'll  try to reconstruct what we did when at work.
Just to be certain - you don't use any threading or even have threads initialized?

shrunk test script - can be run on shell:
---------
function main() {
$fontFile = "arial.ttf";

$surface = new \CairoImageSurface(
    CairoFormat::ARGB32,
    750,
    750
);

$context = new \CairoContext( $surface );
$fontFaceObject = new \CairoFtFontFace($fontFile);
$context->setFontFace( $fontFaceObject );

    for( $i = 0; $i < 3; ++$i ) {
       $angle = rand(1, 360);

        $context->textPath( "blah" . $i );

    }
#	unset($surface, $context);
}

    for( $i = 0; $i < 8000; ++$i ) {
	main();
    }
--------------
php t.php

**Comment by medic123de** [comment]
works for me with:
checking for cairo... found 1.12.14
checking for Freetype... found 16.0.10  (freetype-2.4.11)
checking for fontconfig... found 2.8.0

TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   30
---------------------------------------------------------------------

Number of tests :  447               441
Tests skipped   :    6 (  1.3%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :  441 ( 98.7%) (100.0%)

**Comment by swen100** [comment]
So, i tried it out on another production server.
PHP 5.5.21 debug (fresh install without additional extensions, except cairo)
cairo 1.12.16
Freetype 2.5.0
Fontconfig 2.11

tested with your script.

Same problem, segfault :-(
Backtrace gives me same error (4 lines less than the old ones, because of missing xdebug)

@medic123de did you enable debug-mode for PHP? If i don't enable debug mode i do not get an error-message. But it does not mean that it is stable.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff57d6755 in ft_mem_free () from /usr/lib64/libfreetype.so.6
(gdb) bt
#0  0x00007ffff57d6755 in ft_mem_free () from /usr/lib64/libfreetype.so.6
#1  0x00007ffff57d746c in FT_Stream_ReleaseFrame () from /usr/lib64/libfreetype.so.6
#2  0x00007ffff580f177 in ?? () from /usr/lib64/libfreetype.so.6
#3  0x00007ffff57e3129 in ?? () from /usr/lib64/libfreetype.so.6
#4  0x00007ffff57d969c in ?? () from /usr/lib64/libfreetype.so.6
#5  0x00007ffff57d97a1 in FT_Done_Face () from /usr/lib64/libfreetype.so.6
#6  0x00007ffff57db119 in FT_Done_Library () from /usr/lib64/libfreetype.so.6
#7  0x00007ffff57d1eae in FT_Done_FreeType () from /usr/lib64/libfreetype.so.6
#8  0x00007ffff2498e2b in cairo_ft_font_face_object_destroy (object=0x7ffff7fd12a8) at /usr/src/cairo/cairo_ft_font.c:309
#9  0x00000000009c2ff0 in zend_objects_store_del_ref_by_handle_ex (handle=3, handlers=0x14373e0 <std_object_handlers>) at /usr/src/php-5.5.21/Zend/zend_objects_API.c:226
#10 0x00000000009c2d38 in zend_objects_store_del_ref (zobject=0x7ffff7fd27a8) at /usr/src/php-5.5.21/Zend/zend_objects_API.c:178
#11 0x0000000000988035 in _zval_dtor_func (zvalue=0x7ffff7fd27a8, __zend_filename=0xefccb8 "/usr/src/php-5.5.21/Zend/zend_execute.h", __zend_lineno=81) at /usr/src/php-5.5.21/Zend/zend_variables.c:54
#12 0x00000000009c4b88 in _zval_dtor (zvalue=0x7ffff7fd27a8, __zend_filename=0xefccb8 "/usr/src/php-5.5.21/Zend/zend_execute.h", __zend_lineno=81) at /usr/src/php-5.5.21/Zend/zend_variables.h:35
#13 0x00000000009c4c4f in i_zval_ptr_dtor (zval_ptr=0x7ffff7fd27a8, __zend_filename=0xefcd50 "/usr/src/php-5.5.21/Zend/zend_execute.c", __zend_lineno=1510) at /usr/src/php-5.5.21/Zend/zend_execute.h:81
#14 0x00000000009c99bf in i_free_compiled_variables (execute_data=0x7ffff7f9c258) at /usr/src/php-5.5.21/Zend/zend_execute.c:1510
#15 0x00000000009ca148 in zend_leave_helper_SPEC (execute_data=0x7ffff7f9c258) at /usr/src/php-5.5.21/Zend/zend_vm_execute.h:399
#16 0x00000000009cf36e in ZEND_RETURN_SPEC_CONST_HANDLER (execute_data=0x7ffff7f9c258) at /usr/src/php-5.5.21/Zend/zend_vm_execute.h:2372
#17 0x00000000009ca04e in execute_ex (execute_data=0x7ffff7f9c258) at /usr/src/php-5.5.21/Zend/zend_vm_execute.h:363
#18 0x00000000009ca0d7 in zend_execute (op_array=0x7ffff7fcfd90) at /usr/src/php-5.5.21/Zend/zend_vm_execute.h:388
#19 0x000000000098ba59 in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /usr/src/php-5.5.21/Zend/zend.c:1327
#20 0x00000000008f97e5 in php_execute_script (primary_file=0x7fffffffe310) at /usr/src/php-5.5.21/main/main.c:2506
#21 0x0000000000a3d545 in main (argc=2, argv=0x7fffffffe578) at /usr/src/php-5.5.21/sapi/cgi/cgi_main.c:2459

**Comment by medic123de** [comment]
[root@local cairo.medic]# php -i | grep debug
report_zend_debug => Off => Off

but turning it on does not change anything:
report_zend_debug => On => On

But i don't use xdebug, nor is this a debug build ( configured with --debug ) as far as i can see.

**Comment by swen100** [comment]
i have compiled php with debug enabled (a debug build, as you said):
./configure --enable-debug ...

id don't get a segfault unless i compile PHP with this option enabled.

"report_zend_debug" is new to me. For what does it stand for?

**Comment by medic123de** [comment]
PHP API => 20121113
PHP Extension => 20121212
Zend Extension => 220121212
Zend Extension Build => API220121212,TS
PHP Extension Build => API20121212,TS
Debug Build => no
Thread Safety => enabled
Zend Signal Handling => disabled
Zend Memory Manager => enabled
Zend Multibyte Support => provided by mbstring
IPv6 Support => enabled
DTrace Support => disabled

we dont use debug builds in production for performance resons.
The way how debug information is saved requires another memory managemt strategy,
therefore it's not unlikely, that #2  is due an incompatability with php's debug mode and FT's FaceCache.

Maybe i'll have some time to investigate that next week,
but as said prior: I currently see no relation between #2 and #14, and this fix is for #14 solely.

Certainly one wants to have fixed debug mode too, but that would require to analyze how the Cache is destroyed, which sequence is applied. 
This sounds like a very long singe step session in gnu debugger :-(

**Comment by swen100** [comment]
Hm, o.k. I can live with it. 
Seems you are right and these errors only occur when the debug mode is enabled. No debug-mode no segaults. :-)
So, thanks a lot for the patch!
Bye.

**Comment by swen100** [comment]
I was too fast in giving good news :-(
After including the patched version into a system with higher traffic i get many 
" mod_fcgid: process /srv/www/cgi-bin/php5-wrapper(21231) exit(communication error), get unexpected signal 11"
messages.
So there must be still something bad with this version.

**Comment by medic123de** [comment]
we did load tests here and hadn't had any problem so far.
can you please show where that happened ?  
Eventually it's crashing in the "could not register userdata" handler, which i just added.

**Comment by swen100** [comment]
i would, but i can't
i only get these messages in the apache log:

``
 [fcgid:warn] [pid 26635] (104)Connection reset by peer: [client 188.108.213.245:65226] mod_fcgid: error reading data from FastCGI server
[Fri Feb 06 15:51:30.904378 2015] [fcgid:warn] [pid 26635] (104)Connection reset by peer: [client 188.108.213.245:65226] mod_fcgid: ap_pass_brigade failed in handle_request_ipc function
[Fri Feb 06 15:51:34.255120 2015] [fcgid:error] [pid 26633] mod_fcgid: process /srv/www/cgi-bin/php5-wrapper(26640) exit(communication error), get unexpected signal 11
``

If you know how to get deeper infos without to activate debug mode, please tell me.

**Comment by medic123de** [comment]
Don't you get corefiles?
if this isn't a production server, you can attach gdb  with "gdb -p <pid>" to a child,hit c (continue) 
and issue a bt after it received the segfault.

**Comment by medic123de** [comment]
@auroraeosrose does this satisfy you ?
@swen100 This works for me with Debug Mode. Please test

**Comment by swen100** [comment]
Hi @medic123de, that looks really good :-)
At this point, i get no segfaults, even in debug-mode!

Very strange thing:
what i could find out is, when i use multiple cairo-variables inside unset, e.g. unset(CairoContext, CairoFtFontFace, CairoMatrix) , i get as many segfaults as i create some of them. Do i use unset for every single one, i don't get any segfault-messages.

**Comment by medic123de** [comment]
As said, debug-php really is simle implemented ( which causes several drawbacks). 
You actually even leak file descriptors, because objects are not really destroyed. Unset or 'end of scope' does only decrease refcount, but Debug-PHP holds an additional internal reference. I can not entirely rule out some "double-free" problems here.

For example,if you open a file in constructor and close it in destructor, at least on C level the filedescriptor will leak until the script has finished and the analyzer is running and finally frees the allocated ressources.

So, if  you put your script into a function, and call the function 1024 times. you will most likely end with "out of filedeskriptor error".    
Makes me kinda unhappy :(

**Comment by medic123de** [comment]
@swen100 
can  you  please raise a new  issue with PHP debug and your current  segfaults backtrace?

**Comment by auroraeosrose** [comment]
I"m closing this in favor of the other pr

**Pull request closed without merging**
